# Import IR Data

This tutorial shows the specifics related to infrared data import in Spectrochempy. As prerequisite, the user is
expected to have read the [Import Tutorial](import.ipynb).

Let's first import spectrochempy:

In [1]:
import spectrochempy as scp

<img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAAlw
 SFlzAAAJOgAACToB8GSSSgAAAetpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6
 bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8x
 OTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAg
 eG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMu
 YWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+bWF0cGxvdGxpYiB2ZXJzaW9uIDIuMS4wLCBo
 dHRwOi8vbWF0cGxvdGxpYi5vcmcvPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6
 T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgqNQaNYAAAGiUlE
 QVRIDY1We4xU1Rn/3XPuYx47u8w+hnU38hTcuoUEt/6D2y4RB0ME1BoEd9taJaKh9CFiN7YGp7appUAMNmktMZFoJTYVLVQ0smsy
 26CN0SU1QgsuFAaW3WVmx33N677O6XfuyoIxTXqSO/fec+75fd93vt/3/UbDV0aKSZmCpkFMLz3T9utuu2N+o98aDSMBKVAo89z5
 y+zEz3ZafcCOfvWdlGCalqKn1Bf71CygTd+mf1esSOnpdMpTb+vWpTZuWVfe3jLPa5tzHYNm0T5N0gpdkkHaDBeGBU6d1/t/fyS8
 +/CbqdfUvmsx1PuMgc2bNxv79u1zgd31r+7JH1jbIZKxWRXAcYUQ8IWvBfBXNjEuJWPgMA02NR7C3/pYT9fjdZ3A9tGrWF8YSJHn
 qcDz3y7q2T967PZv+gnYJdd1mEZ+62zGDQV/dQgKhmLzDNOXCEWM3j6eTT5Y3w78dOBKJLR1PQf+4ivPj76UPZnssBN+wbM9Aet/
 AV81Mf1EEULXYfOobvX2WWQk0aoioXwwSmirOlioY0mu8BIouzYl7P8GV3vpqCCEZvlFz769w08oLDWvyKIyL1asSm28d6WfzA97
 ztvvV1kexUMsmhlkULEkuGYmFYC6AvfUrITnwUKl5K79lkjeSSRRTCTbQPd95e1WzMbZSya74XoXAxctCllCnbECMOjZNGRwvzIX
 nD85wbkMmKK+U045Dtdi8Qp+SAxU2GTg2bYlC9224pgvmSb54vkVTBQYyhUt2KjAMyMmPjwRQW5Mh2WKwJhlBh6jVGagFM84wZnQ
 4bpC0Rt4pk1PbSt0NDcxDA5xryosDHWgtbM0DGZDWLSoiDMDYeQnGVrmOThxLozB0RAaahzkJzjKNqcIQBymJFMkOlN8Dqjpg0XY
 Tx5xO/QbmmUrqIjGJznq47TqTaClKYfjp+PInLMwnOdYvtQBZ2XcunQY+VwIo4U4muoFEjVEFE6lQyEUKzHYfgQG9ylCyngU+Cxj
 tOqxCDGHcCsOMCs6iQul5ZiStdATYxjMZXDLTUVwLY8Jey4uOh2IxjwsrP8UXJYxUrkZrghBahzV5iXU6gNkq0Z1EzIsUBUSCV2n
 EOHo0LVxHCpuxabJJdhi5PFnvw5vLXwXIfNZvD/+JNo/X40NegE54sUaazl+UL8XD1x+FB9Ijjt4EQfdGN6J/x131LwIV9ap/AYs
 0x1fz1ZKFbh6A7qKy/By9Dg6G36Ep91vUJJ15Cqr0Z67E8/HzmBrw1OwxWyM+3Mo6BAuSB17oyfx0Oyl2DN0Hqs/70Cx6hBCvESF
 UY1ShWXZZEE7OTAYxZzaPH4TuoiusZvRnunFy2NbiHYuBp2vB66srX4vMEjpRKPxKXmnoQ4+Mn4DPiv8CYcrs3GfNUXJLtM+alSO
 hrMj/KT+wBNW3+E/2liywNO3iSflbaFva/+stGDTxE0E9Sjaox8HBhxpEamzMGSEaFKg+mjEddzDh1MxTDq3YV1kGBsjfwW3S9Cq
 anjmko+ndlb1UR3s6K8JlfphNWq9Ew/7c61T2BB/EbcaNkb8GBaE0tANH7/M34PLdhJDzjIcL9xPbdTG6zyM72Y+wXPHmvB489No
 fm0b5HnbQ9Rgp/7DSSd29AeVvPeNyK6JcYl/yQVi5dBjuGvoV/gaJe47s45QUxrDmcYX0MBsdF7egvXZ7+O0vZA4X8QmOQWjlSK7
 RDz5wIM30gp9UbWcGjXxhzdDu1SiNSpx6kcQB57rPnr/3dlkZarWLnlRq5oPET1dOCIOk4wALib9eeS5iygfhkd09H0DWphB/+gs
 +PcOAS+ssrFmmXXgVfR0de9cpbAJfH3Q1jofW9DZk56dDcVsq9YcsoUMEd1qyLoT3BX1YiyHMJuk97hyjqIoE91t+NcTLeN0ZrfM
 oXatZbu6G0h4VG+ibqq0IJVK6cAjo6serG3vSUezCMct0yQeSOFJSUImqb2qbknUpDqlZxE0QZ+ZUpSlZx79h4Nda6zef9dlk121
 JDjbR5XggPRZlRnS6bRQRtLpn4++cuie/Yvn2svmNxuLw9WCcYIl4fEoTEGiSTUqJdfgU+8ROqf1iMkLzS389YtNPXc/PH8l8ONB
 JZkHD+4JtD04HmVEDWWErmBhzV2/2LB1bemJG6krzv2S6NOHUgtEP0Oif5pE/3fHoruP7N8RiP61GArzSwbUhJJQpXJKiKbfr/3b
 IhKq76sKPUdF9NW/LSqfSn6vjv8C45H/6FSgvZQAAAAASUVORK5CYII='
 style='height:25px; border-radius:12px; display:inline-block; float:left; vertical-align:middle'>
 
 
 
 
 
    SpectroChemPy's API - v.0.4.7 © Copyright 2014-2022 - A.Travert & C.Fernandez @ LCS

## Supported file formats

At the time of writing of this tutorial (Scpy v.0.2), spectrochempy has the following readers which are specific
to IR data:

- `read_omnic()` to open omnic (spa and spg) files
- `read_opus()` to open Opus (*.0, ...) files
- `read_jcamp()` to open an IR JCAMP-DX datafile
- `read()` which is the generic reader. The type of data is then deduced from the file extension.

General purpose data exchange formats such as  \*.csv or \*.mat will be treated in another tutorial (yet to come...)
can also be read using:

- `read_csv()` to open csv files
- `read_matlab()` to open .mat files

## Import of OMNIC files

Thermo Scientific [OMNIC](https://www.thermofisher.com/search/results?query=OMNIC) software
have two proprietary binary file formats:

- .spa files that handle single spectra
- .spg files which contain a group of spectra

Both have been reverse engineered, hence allowing extracting their key data. The Omnic reader of
 Spectrochempy (`read_omnic()`) has been developed based on posts in open forums on the .spa
 file format and extended to .spg file formats.


### a) import spg file

Let's import an .spg file from the `datadir` (see [Import Tutorial](import.ipynb)) and display its main attributes:

In [2]:
X = scp.read_omnic("irdata/CO@Mo_Al2O3.SPG")
X

NDDataset: [float64] a.u. (shape: (y:19, x:3112))

The displayed attributes are detailed in the following.

- `name` is the name of the group of spectra as it appears in the .spg file. OMNIC sets this name to the .spg
filename used at the creation of the group. In this example, the name ("Group sust Mo_Al2O3_base line.SPG") differs
from the filename ("CO@Mo_Al2O3.SPG") because the latter has been changed from outside OMNIC (directly in the OS).

- `author` is that of the creator of the NDDataset (not of the .spg file, which, to our knowledge, does not have
this type of attribute). The string is composed of the username and of the machine name as given by the OS:
username@machinename. It can be accessed and changed using `X.author`.

- `created` is the creation date of the NDDataset (again not that of the .spg file). It can be accessed (or even
changed) using `X.created`.

- `description` indicates the complete pathname of the .spg file. As the pathname is also given in the history (below)
, it can be a good practice to give a self explaining description of the group, for instance:

In [3]:
X.description = "CO adsorption on CoMo/Al2O3, difference spectra"
X.description

'CO adsorption on CoMo/Al2O3, difference spectra'

or directly at the import:

In [4]:
X = scp.read_omnic("irdata//CO@Mo_Al2O3.SPG", description="CO@CoMo/Al2O3, diff spectra")
X.description

'CO@CoMo/Al2O3, diff spectra'

- `history` records changes made to the dataset. Here, right after its creation, it has been sorted by date
(see below).

Then come the attributes related to the data themselves:

- `title` (not to be confused with the `name` of the dataset) describes the nature of data (here **absorbance**).

- `values` shows the data as quantity (with their units when they exist - here a.u. for absorbance units).

- The numerical values ar accessed through the`data` attribute and the units throughout `units` attribute.

In [5]:
X.values

array([[0.0008032, 3.788e-05, ..., 0.0003027, 0.0003745],
       [-3.608e-05, -0.0001981, ..., 0.0003089,  0.00117],
       ...,
       [0.0008357, -0.0001387, ..., -0.0005221, -0.001121],
       [0.0005655, -0.000116, ..., -0.00057, -0.0006307]]) <Unit('absorbance')>

In [6]:
X.data

array([[0.0008032, 3.788e-05, ..., 0.0003027, 0.0003745],
       [-3.608e-05, -0.0001981, ..., 0.0003089,  0.00117],
       ...,
       [0.0008357, -0.0001387, ..., -0.0005221, -0.001121],
       [0.0005655, -0.000116, ..., -0.00057, -0.0006307]])

In [7]:
X.units  # TODO: correct this display

<Unit('absorbance')>

- `shape` is the same as the ndarray `shape` attribute and gives the shape of the data array, here 19 x 3112.

Then come the attributes related to the dimensions of the dataset.

- `x`: this dimension has one coordinate (a `Coord` object) made of the 3112 the wavenumbers.

In [8]:
print(X.x)
X.x

LinearCoord: [float64] cm⁻¹ (size: 3112)


LinearCoord: [float64] cm⁻¹ (size: 3112)

- `y`: this dimension contains:

    - one coordinate made of the 19 acquisition timestamps
    - two labels
        - the acquisition date (UTC) of each spectrum
        - the name of each spectrum.

In [9]:
print(X.y)
X.y

Coord: [float64] s (size: 19)


Coord: [float64] s (size: 19)

- `dims`: Note that the `x` and `y` dimensions are the second and first dimension respectively. Hence, `X[i,j]`
will return
the absorbance of the ith spectrum at the jth  wavenumber. However, this is subject to change, for instance if you
perform operation on your data such as [Transposition](../processing/transformations.ipynb#Transposition). At any time
the attribute `dims` gives the correct names (which can be modified) and order of the dimensions.

In [10]:
X.dims

['y', 'x']

#### Acquisition dates and `y` axis

The acquisition timestamps are the *Unix times* of the acquisition, i.e. the time elapsed in seconds since the
reference date of Jan 1st 1970, 00:00:00 UTC.

In [11]:
X.y.values

array([1.477e+09, 1.477e+09, ..., 1.477e+09, 1.477e+09]) <Unit('second')>

In OMNIC, the acquisition time is that of the start of the acquisition.
As such these may be not convenient to use directly (they are currently in the order of 1.5 billion...)
With this respect, it can be convenient to shift the origin of time coordinate to that of the 1st spectrum,
which has the index `0`:

In [12]:
X.y = X.y - X.y[0]
X.y.values

array([       0,      271, ...,     7918,     8222]) <Unit('second')>

Note that you can also use the inplace subtract operator to perform the same operation.

In [13]:
X.y -= X.y[0]

It is also possible to use the ability of SpectroChemPy to handle unit changes. For this one can use the `to` or
`ito` (
inplace) methods.
```ipython3
val = val.to(some_units)
val.ito(some_units)   # the same inplace
```

In [14]:
X.y.ito("minute")
X.y.values

array([       0,    4.517, ...,      132,      137]) <Unit('minute')>

As shown above, the values of the `Coord` object are accessed through the `values` attribute. To get the last
values corresponding to the last row of the `X` dataset, you can use:

In [15]:
tf = X.y.values[-1]
tf

137.03333333333333 <Unit('minute')>

Negative index in python indicates the position in a sequence from the end, so -1 indicate the last element.

Finally, if for instance you want the `x` time axis to be shifted by 2 minutes, it is also very easy to do so:

In [16]:
X.y = X.y + 2
X.y.values

array([       2,    6.517, ...,      134,      139]) <Unit('minute')>

or using the inplace add operator:
```ipython3
X.y += 2
```

#### The order of spectra

The order of spectra in OMNIC .spg files depends on the order in which the spectra were included in the OMNIC
window before the group was saved. By default, spectrochempy reorders the spectra by acquisition date but the
original OMNIC order can be kept using the `sortbydate=True` at the function call. For instance:

In [17]:
X2 = scp.read_omnic("irdata/CO@Mo_Al2O3.SPG", sortbydate=False)

In the present case, this will change nothing because the spectra in the OMNIC file were already ordered by
increasing data.

Finally, it is worth mentioning that a `NDDataset` can generally be manipulated as numpy ndarray. Hence, for
instance, the following will inverse the order of the first dimension:

In [18]:
X = X[::-1]  # reorders the NDDataset along the first dimension going backward
X.y.values  # displays the `y` dimension

array([     139,      134, ...,    6.517,        2]) <Unit('minute')>

<div class='alert alert-info'>
<b>Note</b>

**Case of groups with different wavenumbers**<br/>
An OMNIC .spg file can contain spectra having different wavenumber axes (e.g. different spacings or wavenumber
ranges). In its current implementation, the spg reader will purposely return an error because such spectra
*cannot* be included in a single NDDataset which, by definition, contains items that share common axes or dimensions !
Future releases might include an option to deal with such a case and return a list of NDDatasets. Let us know if you
are interested in such a feature, see [Bug reports and enhancement requests]
(https://www.spectrochempy.fr/dev/dev/issues.html).


### b) Import of .spa files

The import of a single spectrum follows exactly the same rules as that of the import of a group:

In [19]:
Y = scp.read_omnic("irdata/subdir/7_CZ0-100_Pd_101.SPA")
Y

NDDataset: [float64] a.u. (shape: (y:1, x:5549))

The omnic reader can also import several spa files together, providing that they share a common axis for the
wavenumbers. This is the case of the following files in the irdata/subdir directory: "7_CZ0-100 Pd_101.SPA", ...,
"7_CZ0-100 Pd_104.spa". It is possible to import them in a single NDDataset by using the list of filenames
in the function call:

In [20]:
list_files = [
    "7_CZ0-100_Pd_101.SPA",
    "7_CZ0-100_Pd_102.SPA",
    "7_CZ0-100_Pd_103.SPA",
    "7_CZ0-100_Pd_104.SPA",
]
X = scp.read_omnic(list_files, directory="irdata/subdir")
print(X)

NDDataset: [float64] a.u. (shape: (y:4, x:5549))


When compatible .spa files are alone in a directory, a very convenient is to call the read_omnic method
using only the directory path as argument that will gather the .spa files together:

In [21]:
X = scp.read_omnic("irdata/subdir/1-20")
print(X)

NDDataset: [float64] a.u. (shape: (y:3, x:5549))


<div class='alert alert-warning'>
<b>Warning</b>

There is a difference in specifying the directory to read as an argument as above or as a keyword like here:
```ipython3
X = scp.read_omnic(directory='irdata/subdir')
```
in the latter case, a **dialog** is opened to select files in the given directory, while in the former,
the file are read silently and concatenated (if possible).
</div>

## Import of Bruker OPUS files

[Bruker OPUS](https://www.bruker.com/en/products-and-solutions/infrared-and-raman/opus-spectroscopy-software.html)
files have also a proprietary file format. The Opus reader (`read_opus()`)
of spectrochempy is essentially a wrapper of the python module
[brukeropusreader](https://github.com/spectrochempy/brukeropusreader) developed by QED. It imports absorbance
spectra (the AB block), acquisition times and name of spectra.

The use of `read_opus()` is similar to that of  `read_omnic()` for .spa files. Hence, one can open sample
Opus files contained in the `datadir` using:

In [22]:
Z = scp.read_opus(["test.0000", "test.0001", "test.0002"], directory="irdata/OPUS")
print(Z)

NDDataset: [float64] a.u. (shape: (y:3, x:2567))


or:

In [23]:
Z2 = scp.read_opus("irdata/OPUS")
print(Z2)

NDDataset: [float64] a.u. (shape: (y:4, x:2567))


Note above that a warning was issued because the `irdata/OPUS` contains a background file
(single beam) which is not read by SpectroChemPy.

Finally, supplementary information can be obtained by the direct use of
`brukeropusreader`.

For instance:

In [24]:
from brukeropusreader import read_file  # noqa: E402

opusfile = scp.DATADIR / "irdata" / "OPUS" / "test.0000"  # the full path of the file
Z3 = read_file(opusfile)  # returns a dictionary of the data and metadata extracted
for key in Z3:
    print(key)

Z3["Optik"]  # looks what is the Optik block:

Text Information
Optik
Fourier Transformation
Acquisition
Sample
IgSm
IgSm Data Parameter
PhSm
ScSm
AB
Instrument (Rf)
Optik (Rf)
Acquisition (Rf)
Fourier Transformation (Rf)
IgRf
IgRf Data Parameter
ScRf Data Parameter
ScRf
History
AB Data Parameter
ScSm Data Parameter
PhSm Data Parameter
Instrument


{'ACC': 'Compartiment Echantillon #1112355F',
 'APT': '1.5 mm',
 'BMS': 'KBr',
 'CHN': 'Sample Compartment',
 'DTC': 'LN-MCT Photovoltaic 1mm 8H Fast [Internal Pos.2]',
 'HPF': '0',
 'LPF': '40.',
 'OPF': 'Open',
 'PGN': '3',
 'RDX': '0',
 'SRC': 'MIR',
 'VEL': '120',
 'SON': 'Off'}

## Import/Export of JCAMP-DX files

[JCAMP-DX](http://www.jcamp-dx.org/) is an open format initially developed for IR data and extended to
other spectroscopies. At present, the JCAMP-DX reader implemented in Spectrochempy is limited to IR data and
AFFN encoding (see R. S. McDonald and Paul A. Wilks, JCAMP-DX: A Standard Form for Exchange of Infrared Spectra in
Readable Form, Appl. Spec., 1988, 1, 151–162. doi:10.1366/0003702884428734 for details).

The JCAMP-DX reader of spectrochempy has been essentially written to read again the jcamp-dx files exported by
spectrochempy `write_jdx()` writer.

Hence, for instance, the first dataset can be saved in the JCAMP-DX format:

In [25]:
S0 = X[0]
print(S0)
S0.write_jcamp("CO@Mo_Al2O3_0.jdx", confirm=False)

NDDataset: [float64] a.u. (shape: (y:1, x:5549))


PosixPath('/home/runner/work/spectrochempy/spectrochempy/docs/userguide/importexport/CO@Mo_Al2O3_0.jdx')

Then used (and maybe changed) by a 3rd party software, and re-imported in spectrochempy:

In [26]:
newS0 = scp.read_jcamp("CO@Mo_Al2O3_0.jdx")
print(newS0)

NDDataset: [float64] a.u. (shape: (y:1, x:5549))


It is important to note here that the conversion to JCAMP-DX changes the last digits of absorbance and wavenumbers:

In [27]:
def difference(x, y):
    from numpy import max, abs

    nonzero = y.data != 0
    error = abs(x.data - y.data)
    max_relative_error = max(error[nonzero] / abs(y.data[nonzero]))
    return max(error), max_relative_error

In [28]:
max_error, max_rel_error = difference(S0, newS0)
print(f"Max absolute difference in absorbance: {max_error:.3g}")
print(f"Max relative difference in absorbance: {max_rel_error:.3g}")

Max absolute difference in absorbance: 2.38e-07
Max relative difference in absorbance: 1.19e-07


In [29]:
max_error, max_rel_error = difference(S0.x, newS0.x)
print(f"Max absolute difference in wavenumber: {max_error:.3g}")
print(f"Max relative difference in wavenumber: {max_rel_error:.3g}")

Max absolute difference in wavenumber: 0.0005
Max relative difference in wavenumber: 7.21e-07


This is much beyond the experimental accuracy but can lead to undesirable effects.

For instance:

In [30]:
try:
    S0 - newS0
except Exception as e:
    scp.error_(e)

returns an error because of the small shift of coordinates. We will see in another tutorial how to re-align datasets
and deal with these small problems. It is worth noticing that similar distortions arise in commercial software,...
except that the user is not notified.
